spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 797817936580-tuc8ipc37l9fge52e335r0sagevaqmu4.apps.googleusercontent.com
            client-secret: f8n8RCetObM_IvKYbsjIFE2f
            #            client-name: Web client 1
            #            provider: google
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - https://www.googleapis.com/auth/calendar
              - https://www.googleapis.com/auth/userinfo.profile
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent

server:
  error:
    include-stacktrace: never

omdbkey: 57c2e939
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

#management:
#  endpoints:
#    web:
#      exposure:
#        include: info, health, metrics, httptrace
